Made working with PHP8.0
Keylogic-Software/PopcatPHP pull request #2
Opened 2023-01-10 21:34 UTC by FoxWorn3365

I report what I indicated in the description of the commit:

> In PHP 8.0 it is not possible to access a class quickly if it is not static

I also took the liberty of modifying the "welcome" function to make it more configurable.
Now you can use it like this:
```php
$class = new \Keylogic\Popcatwrapper\Main();
$image = $class->welcome('https://... avatar ...', 'FoxWorn3365', $class->makeServer('A good server', true), 255);
// But we can also do this:
$image = $class->welcome('https://... avatar ...', 'FoxWorn3365', 'Welcome to THE server!', 255);
```

2023-09-27 12:11 UTC, freezemage0 requested changes
I don't agree with making everything `static`.

Static methods cannot be mocked-up, potentially ruining any unit testing for a project that uses this package.

Writing `(new Main)->method()` takes more or less the same time as `Main::method()`.

Overall, this entire class should be split-up, it's a "God object" now (= not good). I would segregate every method into a concrete class, then I would introduce concrete objects (instead of `stdClass`) for methods that need to return object-structured data. This is optional for now, but should be taken to consideration at some point in development.

2023-09-27 12:11 UTC, freezemage0 commented on src/Main.php
> +    return "https://api.popcat.xyz/welcomecard?background={$background}&text1={$name}&text2={$server}&text3=Member+{$newmembercount}&avatar={$avatar}";
This should use `http_build_query()` built-in PHP function instead of building query string by hand.

2023-09-27 12:11 UTC, freezemage0 commented on src/Main.php
>      return json_decode(file_get_contents("https://api.popcat.xyz/color/".$hex));
`file_get_contents()` is hella slow. This should use `curl` PHP extension or any HTTP client implementation.

This comment applies to every method that uses `file_get_contents()` in order to make HTTP requests.

2023-09-27 12:11 UTC, freezemage0 commented on src/Main.php
>      return json_decode(file_get_contents("https://api.popcat.xyz/lyrics?song=".$songname));
What if `json_decode()` fails for some reason? This method lacks after-decode validation.

This comment applies to every method that uses `json_decode()`.

2024-04-07 09:57 UTC, givinghawk commented
PR has been left for over 7 months, closing now.

2024-04-07 09:57 UTC, closed without merging